"""build_agents.py — agent hat file generation for Research Vault.

When to use: ``rv build-agents [--project <slug>]`` to regenerate agent hat
files from the role registry and role-doc templates.

All path resolution goes through Config — zero hardcoded paths or codenames.
Stdlib only.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from .config import Config, load_config


# ---------------------------------------------------------------------------
# Hat generation
# ---------------------------------------------------------------------------

def _hat_header(project_slug: str, role: str, source_dir: str) -> str:
    """Generate a minimal agent hat stub for a project+role combination."""
    return (
        f"# Agent hat: {role} for {project_slug}\n\n"
        f"<!-- Generated by rv build-agents — edit the role docs to update. -->\n\n"
        f"**Project:** {project_slug}\n"
        f"**Role:** {role}\n"
        f"**Source directory:** {source_dir}\n\n"
        f"See the role-doc template for the full role description.\n"
    )


def cmd_build(
    project_slug: str | None,
    cfg: Config,
    *,
    agents_dir: Path | None = None,
    dry_run: bool = False,
) -> int:
    """Generate agent hat files from the config registry.

    If project_slug is given, only generates hats for that project.
    If None, generates hats for all registered projects.

    Hat files are written to ``cfg.agents_dir/<project>/<role>.md``
    (or the override agents_dir if provided).
    """
    target_dir = agents_dir or cfg.agents_dir

    slugs = [project_slug] if project_slug else cfg.all_project_slugs()
    if not slugs:
        print("No projects registered (rv project add <name> to register one).")
        return 0

    generated = 0
    for slug in slugs:
        try:
            proj = cfg.project(slug)
        except KeyError as e:
            print(f"rv build-agents: {e}", file=sys.stderr)
            return 1

        roster = proj.get("roster", [])
        if not roster:
            print(f"  {slug}: no roster defined — skipping hat generation.")
            continue

        source_dir = proj.get("source_dir", str(cfg.notes_root / slug))
        proj_dir = target_dir / slug
        if not dry_run:
            proj_dir.mkdir(parents=True, exist_ok=True)

        for role in roster:
            hat_path = proj_dir / f"{role}.md"
            content = _hat_header(slug, role, source_dir)
            if dry_run:
                print(f"  (dry-run) would write: {hat_path}")
            else:
                hat_path.write_text(content, encoding="utf-8")
                print(f"  Written: {hat_path}")
            generated += 1

    verb = "would generate" if dry_run else "generated"
    print(f"\nbuild-agents: {verb} {generated} hat file(s).")
    return 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_parser(
    parent: "argparse._SubParsersAction | None" = None,  # type: ignore[type-arg]
) -> argparse.ArgumentParser:
    """Build the argument parser for the ``build-agents`` verb.

    When to use: ``rv build-agents`` to regenerate agent hat files from the
    role registry and role-doc templates. Reads the config for project rosters.
    """
    desc = (
        "Regenerate agent hat files from the role registry. "
        "Hat files are written to agents_dir/<project>/<role>.md."
    )
    if parent is not None:
        p = parent.add_parser("build-agents", help="Regenerate agent hat files.", description=desc)
    else:
        p = argparse.ArgumentParser(prog="rv build-agents", description=desc)

    p.add_argument(
        "--project", default=None,
        help="Project slug (regenerate hats for this project only).",
    )
    p.add_argument(
        "--dry-run", action="store_true",
        help="Preview what would be written without writing.",
    )

    return p


def run(args: argparse.Namespace) -> int:
    """Run the build-agents command. Returns exit code."""
    try:
        cfg = load_config()
    except Exception as e:
        print(f"rv build-agents: config error: {e}", file=sys.stderr)
        return 1

    return cmd_build(
        project_slug=args.project,
        cfg=cfg,
        dry_run=args.dry_run,
    )
