"""build_agents.py — agent hat file generation for Research Vault.

When to use: ``rv build-agents [--project <slug>]`` to regenerate agent hat
files from the role registry and role-doc templates.

All path resolution goes through Config — zero hardcoded paths or codenames.
Stdlib only.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from .config import Config, load_config
from .project import DEFAULT_ROSTER


# ---------------------------------------------------------------------------
# CONTRACT stub detection
# ---------------------------------------------------------------------------

# The scaffold banner injected by rv project new into every CONTRACT.md.
# Its presence (combined with >= 1 FILL marker) identifies an unfilled stub.
_CONTRACT_SCAFFOLD_BANNER = "Auto-scaffolded by `rv project new`"
_CONTRACT_FILL_MARKER = "<!-- FILL"


def _is_contract_stub(text: str | None) -> bool:
    """Return True if ``text`` is an unfilled CONTRACT scaffold.

    Stub = the scaffold banner is still present AND at least one <!-- FILL
    marker remains.  A filled CONTRACT removes the banner (or all markers).
    None (missing file) is not a stub — it's missing; caller handles that.
    """
    if not text:
        return False
    return (
        _CONTRACT_SCAFFOLD_BANNER in text
        and _CONTRACT_FILL_MARKER in text
    )


def _load_contract_text(proj_dir: Path) -> str | None:
    """Read CONTRACT.md from ``proj_dir``.  Returns None if the file is absent."""
    contract_path = proj_dir / "CONTRACT.md"
    try:
        return contract_path.read_text(encoding="utf-8")
    except (FileNotFoundError, OSError):
        return None


# ---------------------------------------------------------------------------
# Hat generation
# ---------------------------------------------------------------------------

# Sentinel object so _hat_header can distinguish "not passed" from None (missing).
_MISSING = object()


def _hat_header(
    project_slug: str,
    role: str,
    source_dir: str,
    *,
    contract_text: str | None = _MISSING,  # type: ignore[assignment]
) -> str:
    """Generate an agent hat for a project+role combination.

    contract_text:
      - (default sentinel ``_MISSING``) — backward-compat path: emit a placeholder
        note. Callers should pass the value explicitly.
      - str — the CONTRACT.md content to embed.  Stub vs filled is detected
        automatically; stubs get a nudge banner, filled contracts compose clean.
      - None — CONTRACT.md is absent; a loud NO-CONTRACT banner is embedded.
    """
    # Resolve the contract section
    if contract_text is _MISSING:
        # Backward-compat: called without explicit contract_text
        contract_section = (
            "> (no project lens — re-run `rv build-agents` to compose the CONTRACT)\n"
        )
    elif contract_text is None:
        # Missing CONTRACT
        contract_section = (
            f"> WARNING: NO CONTRACT — this project has no lens file "
            f"(agents_dir/{project_slug}/CONTRACT.md is absent). "
            f"Run `rv project new` to scaffold one, or create it manually, "
            f"then re-run `rv build-agents --project {project_slug}` to re-bake the hats.\n"
        )
    elif _is_contract_stub(contract_text):
        # Stub CONTRACT (scaffolded but not yet filled)
        contract_section = (
            f"> NOTE: CONTRACT is an unfilled stub — fill every <!-- FILL --> "
            f"placeholder and re-run `rv build-agents --project {project_slug}` "
            f"to compose the real project lens into this hat.\n\n"
        ) + contract_text
    else:
        # Filled CONTRACT — embed it directly
        contract_section = contract_text

    return (
        f"# Agent hat: {role} for {project_slug}\n\n"
        f"<!-- Generated by rv build-agents — edit the role docs to update. -->\n\n"
        f"**Project:** {project_slug}\n"
        f"**Role:** {role}\n"
        f"**Source directory:** {source_dir}\n\n"
        f"# Current project lens (CONTRACT)\n\n"
        f"{contract_section}\n"
    )


def cmd_build(
    project_slug: str | None,
    cfg: Config,
    *,
    agents_dir: Path | None = None,
    dry_run: bool = False,
) -> int:
    """Generate agent hat files from the config registry.

    If project_slug is given, only generates hats for that project.
    If None, generates hats for all registered projects.

    Hat files are written to ``cfg.agents_dir/<project>/<role>.md``
    (or the override agents_dir if provided).

    CONTRACT composing: reads cfg.agents_dir/<slug>/CONTRACT.md and embeds it
    in each hat.  Missing -> WARN loudly on stderr + NO-CONTRACT banner in hat.
    Stub (unfilled) -> nudge WARN on stderr + stub banner in hat.
    """
    target_dir = agents_dir or cfg.agents_dir

    slugs = [project_slug] if project_slug else cfg.all_project_slugs()
    if not slugs:
        print("No projects registered (rv project add <name> to register one).")
        return 0

    generated = 0
    for slug in slugs:
        try:
            proj = cfg.project(slug)
        except KeyError as e:
            print(f"rv build-agents: {e}", file=sys.stderr)
            return 1

        roster = proj.get("roster", []) or DEFAULT_ROSTER
        # An empty/missing roster is treated as DEFAULT_ROSTER (belt-and-suspenders
        # for legacy projects that pre-date the default-roster rule).

        source_dir = proj.get("source_dir", str(cfg.notes_root / slug))
        proj_dir = target_dir / slug
        if not dry_run:
            proj_dir.mkdir(parents=True, exist_ok=True)

        # Load and validate the CONTRACT for this project
        contract_text = _load_contract_text(proj_dir)
        if contract_text is None:
            print(
                f"rv build-agents: WARNING — {slug}: no CONTRACT.md found at "
                f"{proj_dir / 'CONTRACT.md'}. "
                f"Run `rv project new` to scaffold one. "
                f"Hats will include a NO-CONTRACT banner.",
                file=sys.stderr,
            )
        elif _is_contract_stub(contract_text):
            print(
                f"rv build-agents: NOTE — {slug}: CONTRACT.md is still an unfilled stub. "
                f"Fill every <!-- FILL --> placeholder then re-run "
                f"`rv build-agents --project {slug}`. "
                f"Hats will include a stub banner.",
                file=sys.stderr,
            )

        for role in roster:
            hat_path = proj_dir / f"{role}.md"
            content = _hat_header(slug, role, source_dir, contract_text=contract_text)
            if dry_run:
                print(f"  (dry-run) would write: {hat_path}")
            else:
                hat_path.write_text(content, encoding="utf-8")
                print(f"  Written: {hat_path}")
            generated += 1

    verb = "would generate" if dry_run else "generated"
    print(f"\nbuild-agents: {verb} {generated} hat file(s).")
    return 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_parser(
    parent: "argparse._SubParsersAction | None" = None,  # type: ignore[type-arg]
) -> argparse.ArgumentParser:
    """Build the argument parser for the ``build-agents`` verb.

    When to use: ``rv build-agents`` to regenerate agent hat files from the
    role registry and role-doc templates. Reads the config for project rosters.
    """
    desc = (
        "Regenerate agent hat files from the role registry. "
        "Hat files are written to agents_dir/<project>/<role>.md."
    )
    if parent is not None:
        p = parent.add_parser("build-agents", help="Regenerate agent hat files.", description=desc)
    else:
        p = argparse.ArgumentParser(prog="rv build-agents", description=desc)

    p.add_argument(
        "--project", default=None,
        help="Project slug (regenerate hats for this project only).",
    )
    p.add_argument(
        "--dry-run", action="store_true",
        help="Preview what would be written without writing.",
    )

    return p


def run(args: argparse.Namespace) -> int:
    """Run the build-agents command. Returns exit code."""
    try:
        cfg = load_config()
    except Exception as e:
        print(f"rv build-agents: config error: {e}", file=sys.stderr)
        return 1

    return cmd_build(
        project_slug=args.project,
        cfg=cfg,
        dry_run=args.dry_run,
    )
