"""init.py — `rv init` — scaffold a fresh Research Vault instance.

When to use: ``rv init [<dir>]`` to scaffold a new multi-project Research Vault
instance in the given directory (or the current directory). Creates the instance
root with config, control files, task dirs, doctrine, notes root (OKF type dirs),
and the two canned demo projects (demo-research + demo-litreview).

SR-CCB additions:
  ``rv init`` also scaffolds the Claude Code binding so a bare
  ``rv init && claude`` boots Alfred + the full crew:
    1. Writes ``CLAUDE.md`` at the instance root (the hub-bootstrap: tells a
       fresh ``claude`` session that it IS Alfred, the hub).
    2. Creates an empty ``.claude/agents/`` dir (CC's session-start requirement:
       the watcher only registers dirs that exist before the session opens).
    3. Auto-runs ``build-agents --target claude-code`` to populate
       ``.claude/agents/<role>.md`` with CC-format subagent files for the
       DEFAULT_ROSTER (5 roles) + architect = 6 files (charter + role doctrine,
       vault-level — no per-project lens; SR-LENS-RM).

Multi-repo topology note:
  The `examples/` demo projects are shipped inside the package under
  ``src/research_vault/data/examples/`` and copied on ``rv init``.
  A REAL project is a separate git repo at an external source_dir, registered
  by ``rv project add``.
  ``rv init`` scaffolds the INSTANCE ROOT — it does NOT scaffold new projects as
  subdirs (that would re-introduce the monorepo pattern; use ``rv project add`` +
  the deferred ``rv project new`` capstone for real projects).

Package data layout (SR-PKG):
  All files copied by ``rv init`` live under ``src/research_vault/data/`` inside
  the wheel.  They are loaded via ``importlib.resources`` + ``as_file()`` so the
  copy works from a regular wheel install AND from a zipped wheel (zipimport-safe).
  There are NO ``__file__``-based fallbacks — a missing data file is a HARD ERROR,
  not a silent skeleton (charter §2: surface, never silently degrade).

Stdlib only. No external deps.
"""
from __future__ import annotations

import argparse
import importlib.resources
import shutil
import sys
from pathlib import Path

from .note import scaffold_okf_dirs


# ---------------------------------------------------------------------------
# Config template
# ---------------------------------------------------------------------------

_CONFIG_TEMPLATE = """\
# research_vault.toml — Research Vault instance configuration
# Generated by `rv init`. Edit to add real projects and customise paths.
#
# Multi-repo topology: real projects are SEPARATE repos registered via `rv project add`.
# The demo-research and demo-litreview entries below are in-repo examples only.
#
# See QUICKSTART.md for the next steps.

instance_root = "{instance_root}"
notes_root = "{notes_root}"
state_dir = "{state_dir}"
agents_dir = "{agents_dir}"
tasks_dir = "{tasks_dir}"
control_dir = "{control_dir}"

[adapters]
notifier = "file"
backend = "local"
secrets = "env"

# ── Demo projects (in-repo subdirs for zero-setup demonstration) ─────────────
# These point into the examples/ directory for the demo loops.
# Add REAL projects below as separate repos via `rv project add`.

[projects.demo-research]
source_dir = "{demo_research_dir}"
tasks_dir = "{tasks_dir}/demo-research"
control_file = "{control_dir}/demo-research.md"

[projects.demo-litreview]
source_dir = "{demo_litreview_dir}"
tasks_dir = "{tasks_dir}/demo-litreview"
control_file = "{control_dir}/demo-litreview.md"

# ── To add a real project ────────────────────────────────────────────────────
# Either run:
#   rv project add my-project /absolute/path/to/my-project-repo
#
# Or add manually:
# [projects.my-project]
# source_dir = "/absolute/path/to/my-project-repo"

# ── Manuscript review-board tuning (D-REV knobs) ─────────────────────────────
# Uncomment and adjust to tune the adversarial review-board gate (rv manuscript review).
# Defaults are safe; only change if you have a specific reason (see §5J.17.9 D-REV).
#
# [manuscript_review]
# max_rounds         = 2     # N: review rounds before NOT-CLEARED (hard-cap 3)
# reviewers_per_round = 3    # K: independent lenses per round (min 2; K=2 → L1+L3)
# floor_dimensions   = ["SOUND", "REPRO"]  # dims that gate automatically (others surface-only)
# floor_value        = 3     # minimum per-floor-dim score to clear (1–5 scale; 3=borderline)
# aggregation        = "min" # MIN-across-reviewers (the worst reviewer gates — not the mean)
"""

# ---------------------------------------------------------------------------
# Control file template
# ---------------------------------------------------------------------------

_CONTROL_TEMPLATE = """\
# CONTROL — {project}

The manager bus for this project: an async, durable handshake file.
READ via `rv status {project}` or `rv control {project} check`.
WRITE via `rv control {project} post <text>` — never by hand.

> *Created by `rv init`.*

## Inbox  (hub/owner → manager)
  _(none)_

## Handshakes  (in-flight, needs the other side)
  _(none)_

## Outbox  (manager → hub/owner)
  _(none)_

## Open / blockers
  _(none)_
"""

# ---------------------------------------------------------------------------
# DEVLOG template
# ---------------------------------------------------------------------------

_DEVLOG_TEMPLATE = """\
# DEVLOG

Newest entry on top. One entry per working day.
Sections: ### Done · ### Decisions · ### Open / next

---

## {today} — Instance initialised

### Done
- `rv init` scaffolded this Research Vault instance.
- Demo projects registered: demo-research, demo-litreview.

### Decisions
- Instance root: `{instance_root}`

### Open / next
- Run `rv check` to verify prerequisites.
- Start a demo loop: `rv dag run examples/demo-research/research-loop.json`
- Add a real project: `rv project add <slug> <path>`
"""

# ---------------------------------------------------------------------------
# architecture.md template
# ---------------------------------------------------------------------------

_ARCHITECTURE_TEMPLATE = """\
# Architecture

This file documents the structure and design decisions for this Research Vault instance.

## Instance layout

```
{instance_root}/
  research_vault.toml   # config SSOT — all paths resolved here
  QUICKSTART.md         # getting-started guide
  DEVLOG.md             # decision log (newest first)
  architecture.md       # this file
  notes/                # central OKF knowledge base
    experiments/        # pre-registration notes (filed before runs)
    findings/           # research findings
    methods/            # method and protocol notes
    literature/         # distilled literature notes
    concepts/           # distilled conceptual claims
    mocs/               # maps of content (link graphs)
  control/              # coordination bus (one file per project)
  tasks/                # task cards (one subdir per project)
  doctrine/             # portable research-assistant doctrine
  .agents/              # agent hat files (generated by rv build-agents)
  examples/             # demo projects (in-repo, for zero-setup demo)
    demo-research/      # research loop demonstration
    demo-litreview/     # lit-review loop demonstration
```

## Multi-project registry

Projects are registered in `research_vault.toml` under `[projects.<slug>]`.
Each project has a `source_dir` pointing to its repository root.

**Demo projects** (in-repo): `demo-research`, `demo-litreview`
**Real projects** (separate repos): register via `rv project add <slug> <path>`

## The two canonical loops

### Research loop (`examples/demo-research/research-loop.json`)

```
plan → plan-critic → [human-go] → run → score → analyze → [human-go]
                                    ↑
                    (blocked until experiments/exp-q1.md is filed)
```

Pre-registration is **structural**: the `run` node has an `afterok` watch on
`note:experiments/exp-q1.md+fresh`. The experiment cannot run until the
pre-registration note exists.

### Lit-review loop (`examples/demo-litreview/lit-review-loop.json`)

```
scope → survey → distill-1 → [okf-coverage-gate] → synthesize → synthesis-critic → [human-go]
                  distill-2 ↗
```

OKF coverage is **structural**: the `okf-coverage-gate` human-go blocks until all
distill nodes succeed. A distill node cannot succeed without its `literature/<key>.md`
note (enforced by `rv dag complete`'s produces check).
"""

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _pkg_data() -> "importlib.resources.abc.Traversable":
    """Return the package data root Traversable (src/research_vault/data/).

    Using ``importlib.resources.files()`` makes the lookup package-relative,
    so it works correctly from a wheel install, an editable install, or a
    zipimport — there is no ``__file__``-based repo-root path.
    """
    return importlib.resources.files("research_vault") / "data"


# ---------------------------------------------------------------------------
# Core init logic
# ---------------------------------------------------------------------------

def cmd_init_in_dir(target_dir: str) -> int:
    """Scaffold a fresh Research Vault instance in target_dir.

    Returns 0 on success, 1 on error.
    This is the programmatic entrypoint (also used by tests).
    """
    import datetime

    target = Path(target_dir).expanduser().resolve()

    # Guard: refuse to overwrite an existing instance
    config_path = target / "research_vault.toml"
    if config_path.exists():
        print(
            f"rv init: {config_path} already exists. "
            "Research Vault is already initialised here. "
            "Remove research_vault.toml to re-initialise.",
            file=sys.stderr,
        )
        return 1

    if not target.exists():
        target.mkdir(parents=True)

    print(f"Initialising Research Vault instance in: {target}")

    # ── Resolve all paths ────────────────────────────────────────────────────
    notes_root = target / "notes"
    state_dir = target / "state"
    agents_dir = target / ".agents"
    tasks_dir = target / "tasks"
    control_dir = target / "control"
    examples_dir = target / "examples"
    demo_research_dir = examples_dir / "demo-research"
    demo_litreview_dir = examples_dir / "demo-litreview"

    # ── Create directory structure ───────────────────────────────────────────
    for d in (
        notes_root,
        state_dir,
        agents_dir,
        tasks_dir / "demo-research",
        tasks_dir / "demo-litreview",
        control_dir,
        examples_dir,
        demo_research_dir,
        demo_litreview_dir,
    ):
        d.mkdir(parents=True, exist_ok=True)
        print(f"  created: {d.relative_to(target)}/")

    # ── Create OKF note type dirs ────────────────────────────────────────────
    scaffold_okf_dirs(notes_root)
    for note_type in sorted({"experiments", "findings", "methods", "literature", "concepts", "mocs"}):
        print(f"  created: notes/{note_type}/")

    # ── Write research_vault.toml ────────────────────────────────────────────
    today_str = datetime.date.today().isoformat()
    config_text = _CONFIG_TEMPLATE.format(
        instance_root=str(target),
        notes_root=str(notes_root),
        state_dir=str(state_dir),
        agents_dir=str(agents_dir),
        tasks_dir=str(tasks_dir),
        control_dir=str(control_dir),
        demo_research_dir=str(demo_research_dir),
        demo_litreview_dir=str(demo_litreview_dir),
    )
    config_path.write_text(config_text, encoding="utf-8")
    print(f"  created: research_vault.toml")

    # ── Write DEVLOG.md ──────────────────────────────────────────────────────
    devlog_text = _DEVLOG_TEMPLATE.format(
        today=today_str,
        instance_root=str(target),
    )
    (target / "DEVLOG.md").write_text(devlog_text, encoding="utf-8")
    print(f"  created: DEVLOG.md")

    # ── Write architecture.md ────────────────────────────────────────────────
    arch_text = _ARCHITECTURE_TEMPLATE.format(instance_root=str(target))
    (target / "architecture.md").write_text(arch_text, encoding="utf-8")
    print(f"  created: architecture.md")

    # ── Write control files ──────────────────────────────────────────────────
    for project in ("demo-research", "demo-litreview"):
        ctrl_text = _CONTROL_TEMPLATE.format(project=project)
        (control_dir / f"{project}.md").write_text(ctrl_text, encoding="utf-8")
        print(f"  created: control/{project}.md")

    # ── Copy QUICKSTART.md from package data (zipimport-safe) ───────────────
    pkg_data = _pkg_data()
    quickstart_dst = target / "QUICKSTART.md"
    with importlib.resources.as_file(pkg_data / "templates" / "QUICKSTART.md") as qs_src:
        if not qs_src.is_file():
            raise RuntimeError(
                "Package data missing: data/templates/QUICKSTART.md. "
                "The wheel is incomplete — reinstall research-vault."
            )
        shutil.copy2(qs_src, quickstart_dst)
    print(f"  created: QUICKSTART.md")

    # ── Copy doctrine/ from package data ─────────────────────────────────────
    doctrine_dst = target / "doctrine"
    with importlib.resources.as_file(pkg_data / "doctrine") as doctrine_src:
        if not doctrine_src.is_dir():
            raise RuntimeError(
                "Package data missing: data/doctrine/. "
                "The wheel is incomplete — reinstall research-vault."
            )
        shutil.copytree(str(doctrine_src), str(doctrine_dst), dirs_exist_ok=True)
    print(f"  created: doctrine/ ({_count_files(doctrine_dst)} files)")

    # ── Copy example loop manifests from package data ────────────────────────
    with importlib.resources.as_file(pkg_data / "examples" / "demo-research") as dr_src:
        if not dr_src.is_dir():
            raise RuntimeError(
                "Package data missing: data/examples/demo-research/. "
                "The wheel is incomplete — reinstall research-vault."
            )
        shutil.copytree(str(dr_src), str(demo_research_dir), dirs_exist_ok=True)
    print(f"  created: examples/demo-research/ ({_count_files(demo_research_dir)} files)")

    with importlib.resources.as_file(pkg_data / "examples" / "demo-litreview") as dl_src:
        if not dl_src.is_dir():
            raise RuntimeError(
                "Package data missing: data/examples/demo-litreview/. "
                "The wheel is incomplete — reinstall research-vault."
            )
        shutil.copytree(str(dl_src), str(demo_litreview_dir), dirs_exist_ok=True)
    print(f"  created: examples/demo-litreview/ ({_count_files(demo_litreview_dir)} files)")

    # ── SR-CCB: Scaffold CLAUDE.md (the Alfred hub-bootstrap) ────────────────
    # Makes a fresh `claude` session become Alfred, the hub.
    # Loaded via importlib.resources (zipimport-safe, same pattern as QUICKSTART).
    claude_md_dst = target / "CLAUDE.md"
    with importlib.resources.as_file(pkg_data / "templates" / "CLAUDE.md.tmpl") as tmpl_src:
        if not tmpl_src.is_file():
            raise RuntimeError(
                "Package data missing: data/templates/CLAUDE.md.tmpl. "
                "The wheel is incomplete — reinstall research-vault."
            )
        shutil.copy2(str(tmpl_src), str(claude_md_dst))
    print(f"  created: CLAUDE.md")

    # ── SR-CCB: Create .claude/agents/ dir (CC session-start requirement) ────
    # CC's file watcher registers .claude/agents/ only if it exists when the
    # session opens.  Create it now (even before populating) so a bare
    # `rv init && claude` works without a manual restart.
    dot_claude_agents = target / ".claude" / "agents"
    dot_claude_agents.mkdir(parents=True, exist_ok=True)
    print(f"  created: .claude/agents/")

    # ── SR-CCB: Auto-run build-agents --target claude-code ───────────────────
    # Populate .claude/agents/<role>.md with CC-format subagent files so the
    # crew is discoverable immediately (zero extra commands for the adopter).
    #
    # IMPORTANT — why we do NOT use load_config() here:
    #   The rv CLI calls load_config() at dispatch time (cli.py: cfg = load_config())
    #   to resolve instance-level plugin verbs.  That call populates the module-level
    #   _CACHE with a stale config — typically the default (no projects, CWD as
    #   instance_root) because `rv init myvault` is run from the PARENT directory
    #   before the new research_vault.toml even exists.  A subsequent load_config()
    #   call here would hit that stale cache regardless of any env-var override, and
    #   the auto-build would write files to the WRONG instance_root.
    #
    #   Fix: construct Config directly from the TOML we just wrote, bypassing the
    #   module-level cache entirely.  This is immune to cache state and always reads
    #   exactly what we persisted above.
    from .config import (
        Config, _load_toml, _expand_paths, _default_config, _merge, reset_config_cache,
    )
    from .build_agents import cmd_build as _cmd_build_agents
    from .project import DEFAULT_ROSTER as _DEFAULT_ROSTER
    try:
        _defaults = _default_config()
        _raw = _load_toml(config_path)
        _merged = _merge(_defaults, _raw)
        # instance_root is written as an absolute path in the TOML by _CONFIG_TEMPLATE;
        # fall back to `target` if somehow absent.
        _instance_root = Path(_merged.get("instance_root", str(target)))
        _merged = _expand_paths(_merged, _instance_root)
        _cfg = Config(_merged, config_file=config_path)
        # Reset the module-level cache so subsequent rv commands in the same process
        # reload from the new instance's config rather than any stale pre-init cache.
        reset_config_cache()

        _rc = _cmd_build_agents(cfg=_cfg, target="claude-code")
        if _rc != 0:
            print(
                "rv init: WARNING — build-agents --target claude-code returned non-zero. "
                "Run `rv build-agents --target claude-code` manually to populate .claude/agents/.",
                file=sys.stderr,
            )
        # Post-build assertion (Argus hardening): verify the expected agent files actually
        # exist.  A silent zero-exit with 0 files is more dangerous than a loud failure.
        _agents_dir = _instance_root / ".claude" / "agents"
        _present = list(_agents_dir.glob("*.md")) if _agents_dir.is_dir() else []
        _expected_count = len(_DEFAULT_ROSTER) + 1  # DEFAULT_ROSTER roles + architect
        if len(_present) < _expected_count:
            _missing = _expected_count - len(_present)
            print(
                f"rv init: ERROR — build-agents wrote {len(_present)} agent file(s) but "
                f"{_expected_count} were expected ({_missing} missing). "
                "The crew is incomplete. "
                "Run `rv build-agents --target claude-code` manually to investigate.",
                file=sys.stderr,
            )
            return 1
    except Exception as exc:
        print(
            f"rv init: WARNING — could not auto-run build-agents (claude-code): {exc}. "
            "Run `rv build-agents --target claude-code` manually to populate .claude/agents/.",
            file=sys.stderr,
        )

    print()
    print("Research Vault instance initialised.")
    print()
    print("Open `claude` in this directory to start — you'll be Alfred, the hub.")
    print("The crew is stood up as subagents in .claude/agents/")
    print()
    print("Next steps:")
    print("  1. rv check                     — verify prerequisites")
    print("  2. rv compute init              — DECLARE your compute (scaffold manifest)")
    print("     rv doctor                    — DISCOVER capabilities per declared backend")
    print("     rv compute show              — VERIFY the merged recipe")
    print("  3. rv dag run examples/demo-research/research-loop.json  — start the research loop demo")
    print("  4. rv dag run examples/demo-litreview/lit-review-loop.json  — start the lit-review demo")
    print("  5. rv project add <slug> <path> — add a real project")
    print()
    print("See QUICKSTART.md for a full walkthrough.")
    return 0


def _count_files(path: Path) -> int:
    """Count files recursively in a directory."""
    return sum(1 for _ in path.rglob("*") if _.is_file())


# ---------------------------------------------------------------------------
# CLI verb
# ---------------------------------------------------------------------------

def build_parser(
    parent: "argparse._SubParsersAction | None" = None,
) -> argparse.ArgumentParser:
    """Build the argument parser for the ``init`` verb.

    When to use: ``rv init [<dir>]`` to scaffold a fresh Research Vault instance
    from templates. Creates the instance root with config, control files, task dirs,
    doctrine, notes root (OKF type dirs), and the two canned demo projects.
    """
    desc = (
        "Scaffold a fresh multi-project Research Vault instance. "
        "Creates research_vault.toml, control/, tasks/, doctrine/, notes/ (OKF type dirs), "
        "examples/demo-research/ + examples/demo-litreview/ demo projects, and QUICKSTART.md. "
        "A real project is a SEPARATE git repo registered via `rv project add`, not a subdir."
    )
    if parent is not None:
        p = parent.add_parser(
            "init",
            help="Scaffold a fresh Research Vault instance from templates.",
            description=desc,
        )
    else:
        p = argparse.ArgumentParser(prog="rv init", description=desc)

    p.add_argument(
        "dir",
        nargs="?",
        default=".",
        help="Directory to initialise (default: current directory).",
    )
    return p


def run(args: argparse.Namespace) -> int:
    """Dispatch: rv init [<dir>]."""
    return cmd_init_in_dir(args.dir)
