"""init.py — `rv init` — scaffold a fresh Research Vault instance.

When to use: ``rv init [<dir>]`` to scaffold a new multi-project Research Vault
instance in the given directory (or the current directory). Creates the instance
root with config, control files, task dirs, doctrine, notes root (OKF type dirs),
and the two canned demo projects (demo-research + demo-litreview).

Multi-repo topology note:
  The `examples/` demo projects are IN-REPO subdirs for zero-setup demonstration.
  Their source_dir points in-repo for the demo. A REAL project is a separate git
  repo at an external source_dir, registered by `rv project add`.
  `rv init` scaffolds the INSTANCE ROOT — it does NOT scaffold new projects as
  subdirs (that would re-introduce the monorepo pattern; use `rv project add` +
  the deferred `rv project new` capstone for real projects).

Stdlib only. No external deps.
"""
from __future__ import annotations

import argparse
import importlib.resources
import json
import shutil
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Config template
# ---------------------------------------------------------------------------

_CONFIG_TEMPLATE = """\
# research_vault.toml — Research Vault instance configuration
# Generated by `rv init`. Edit to add real projects and customise paths.
#
# Multi-repo topology: real projects are SEPARATE repos registered via `rv project add`.
# The demo-research and demo-litreview entries below are in-repo examples only.
#
# See QUICKSTART.md for the next steps.

instance_root = "{instance_root}"
notes_root = "{notes_root}"
state_dir = "{state_dir}"
agents_dir = "{agents_dir}"
tasks_dir = "{tasks_dir}"
control_dir = "{control_dir}"

[adapters]
notifier = "file"
backend = "local"
secrets = "env"

# ── Demo projects (in-repo subdirs for zero-setup demonstration) ─────────────
# These point into the examples/ directory for the demo loops.
# Add REAL projects below as separate repos via `rv project add`.

[projects.demo-research]
source_dir = "{demo_research_dir}"
tasks_dir = "{tasks_dir}/demo-research"
control_file = "{control_dir}/demo-research.md"

[projects.demo-litreview]
source_dir = "{demo_litreview_dir}"
tasks_dir = "{tasks_dir}/demo-litreview"
control_file = "{control_dir}/demo-litreview.md"

# ── To add a real project ────────────────────────────────────────────────────
# Either run:
#   rv project add my-project /absolute/path/to/my-project-repo
#
# Or add manually:
# [projects.my-project]
# source_dir = "/absolute/path/to/my-project-repo"
"""

# ---------------------------------------------------------------------------
# Control file template
# ---------------------------------------------------------------------------

_CONTROL_TEMPLATE = """\
# CONTROL — {project}

The manager bus for this project: an async, durable handshake file.
READ via `rv status {project}` or `rv control {project} check`.
WRITE via `rv control {project} post <text>` — never by hand.

> *Created by `rv init`.*

## Inbox  (hub/owner → manager)
  _(none)_

## Handshakes  (in-flight, needs the other side)
  _(none)_

## Outbox  (manager → hub/owner)
  _(none)_

## Open / blockers
  _(none)_
"""

# ---------------------------------------------------------------------------
# DEVLOG template
# ---------------------------------------------------------------------------

_DEVLOG_TEMPLATE = """\
# DEVLOG

Newest entry on top. One entry per working day.
Sections: ### Done · ### Decisions · ### Open / next

---

## {today} — Instance initialised

### Done
- `rv init` scaffolded this Research Vault instance.
- Demo projects registered: demo-research, demo-litreview.

### Decisions
- Instance root: `{instance_root}`

### Open / next
- Run `rv check` to verify prerequisites.
- Start a demo loop: `rv dag run examples/demo-research/research-loop.json`
- Add a real project: `rv project add <slug> <path>`
"""

# ---------------------------------------------------------------------------
# architecture.md template
# ---------------------------------------------------------------------------

_ARCHITECTURE_TEMPLATE = """\
# Architecture

This file documents the structure and design decisions for this Research Vault instance.

## Instance layout

```
{instance_root}/
  research_vault.toml   # config SSOT — all paths resolved here
  QUICKSTART.md         # getting-started guide
  DEVLOG.md             # decision log (newest first)
  architecture.md       # this file
  notes/                # central OKF knowledge base
    experiments/        # pre-registration notes (filed before runs)
    findings/           # research findings
    methods/            # method and protocol notes
    literature/         # distilled literature notes
    concepts/           # distilled conceptual claims
    mocs/               # maps of content (link graphs)
  control/              # coordination bus (one file per project)
  tasks/                # task cards (one subdir per project)
  doctrine/             # portable research-assistant doctrine
  .agents/              # agent hat files (generated by rv build-agents)
  examples/             # demo projects (in-repo, for zero-setup demo)
    demo-research/      # research loop demonstration
    demo-litreview/     # lit-review loop demonstration
```

## Multi-project registry

Projects are registered in `research_vault.toml` under `[projects.<slug>]`.
Each project has a `source_dir` pointing to its repository root.

**Demo projects** (in-repo): `demo-research`, `demo-litreview`
**Real projects** (separate repos): register via `rv project add <slug> <path>`

## The two canonical loops

### Research loop (`examples/demo-research/research-loop.json`)

```
plan → plan-critic → [human-go] → run → score → analyze → [human-go]
                                    ↑
                    (blocked until experiments/exp-q1.md is filed)
```

Pre-registration is **structural**: the `run` node has an `afterok` watch on
`note:experiments/exp-q1.md+fresh`. The experiment cannot run until the
pre-registration note exists.

### Lit-review loop (`examples/demo-litreview/lit-review-loop.json`)

```
scope → survey → distill-1 → [okf-coverage-gate] → synthesize → synthesis-critic → [human-go]
                  distill-2 ↗
```

OKF coverage is **structural**: the `okf-coverage-gate` human-go blocks until all
distill nodes succeed. A distill node cannot succeed without its `literature/<key>.md`
note (enforced by `rv dag complete`'s produces check).
"""

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _package_template_dir() -> Path:
    """Return the path to the package templates/ directory."""
    pkg = importlib.resources.files("research_vault")
    return Path(str(pkg)) / "templates"


def _package_doctrine_dir() -> Path:
    """Return the path to the installed package's doctrine/ directory.

    We cannot ship doctrine/ inside src/research_vault/ (it's a repo-level
    directory), so we copy from the repo root during init. At install time,
    doctrine/ is NOT part of the wheel — init copies it from the repo if
    available, otherwise skips gracefully.
    """
    # When running from the repo (editable install or direct), doctrine/
    # is two levels up from this file: src/research_vault/init.py → src/ → repo_root/
    repo_root = Path(__file__).parent.parent.parent
    return repo_root / "doctrine"


def _package_examples_dir() -> Path:
    """Return the path to the repo's examples/ directory."""
    repo_root = Path(__file__).parent.parent.parent
    return repo_root / "examples"


# ---------------------------------------------------------------------------
# Core init logic
# ---------------------------------------------------------------------------

def cmd_init_in_dir(target_dir: str) -> int:
    """Scaffold a fresh Research Vault instance in target_dir.

    Returns 0 on success, 1 on error.
    This is the programmatic entrypoint (also used by tests).
    """
    import datetime

    target = Path(target_dir).expanduser().resolve()

    # Guard: refuse to overwrite an existing instance
    config_path = target / "research_vault.toml"
    if config_path.exists():
        print(
            f"rv init: {config_path} already exists. "
            "Research Vault is already initialised here. "
            "Remove research_vault.toml to re-initialise.",
            file=sys.stderr,
        )
        return 1

    if not target.exists():
        target.mkdir(parents=True)

    print(f"Initialising Research Vault instance in: {target}")

    # ── Resolve all paths ────────────────────────────────────────────────────
    notes_root = target / "notes"
    state_dir = target / "state"
    agents_dir = target / ".agents"
    tasks_dir = target / "tasks"
    control_dir = target / "control"
    examples_dir = target / "examples"
    demo_research_dir = examples_dir / "demo-research"
    demo_litreview_dir = examples_dir / "demo-litreview"

    # ── Create directory structure ───────────────────────────────────────────
    for d in (
        notes_root,
        state_dir,
        agents_dir,
        tasks_dir / "demo-research",
        tasks_dir / "demo-litreview",
        control_dir,
        examples_dir,
        demo_research_dir,
        demo_litreview_dir,
    ):
        d.mkdir(parents=True, exist_ok=True)
        print(f"  created: {d.relative_to(target)}/")

    # ── Create OKF note type dirs ────────────────────────────────────────────
    for note_type in ("experiments", "findings", "methods", "literature", "concepts", "mocs"):
        (notes_root / note_type).mkdir(exist_ok=True)
        print(f"  created: notes/{note_type}/")

    # ── Write research_vault.toml ────────────────────────────────────────────
    today_str = datetime.date.today().isoformat()
    config_text = _CONFIG_TEMPLATE.format(
        instance_root=str(target),
        notes_root=str(notes_root),
        state_dir=str(state_dir),
        agents_dir=str(agents_dir),
        tasks_dir=str(tasks_dir),
        control_dir=str(control_dir),
        demo_research_dir=str(demo_research_dir),
        demo_litreview_dir=str(demo_litreview_dir),
    )
    config_path.write_text(config_text, encoding="utf-8")
    print(f"  created: research_vault.toml")

    # ── Write DEVLOG.md ──────────────────────────────────────────────────────
    devlog_text = _DEVLOG_TEMPLATE.format(
        today=today_str,
        instance_root=str(target),
    )
    (target / "DEVLOG.md").write_text(devlog_text, encoding="utf-8")
    print(f"  created: DEVLOG.md")

    # ── Write architecture.md ────────────────────────────────────────────────
    arch_text = _ARCHITECTURE_TEMPLATE.format(instance_root=str(target))
    (target / "architecture.md").write_text(arch_text, encoding="utf-8")
    print(f"  created: architecture.md")

    # ── Write control files ──────────────────────────────────────────────────
    for project in ("demo-research", "demo-litreview"):
        ctrl_text = _CONTROL_TEMPLATE.format(project=project)
        (control_dir / f"{project}.md").write_text(ctrl_text, encoding="utf-8")
        print(f"  created: control/{project}.md")

    # ── Copy QUICKSTART.md from package templates ────────────────────────────
    tmpl_dir = _package_template_dir()
    quickstart_src = tmpl_dir / "QUICKSTART.md"
    quickstart_dst = target / "QUICKSTART.md"
    if quickstart_src.exists():
        shutil.copy2(quickstart_src, quickstart_dst)
        print(f"  created: QUICKSTART.md")
    else:
        # Fallback: write a minimal quickstart
        quickstart_dst.write_text(
            "# Research Vault\n\nRun `rv check` to verify prerequisites.\n"
            "Run `rv help` to see all verbs.\n",
            encoding="utf-8",
        )
        print(f"  created: QUICKSTART.md (minimal fallback)")

    # ── Copy doctrine/ from repo ─────────────────────────────────────────────
    doctrine_src = _package_doctrine_dir()
    doctrine_dst = target / "doctrine"
    if doctrine_src.exists() and doctrine_src.is_dir():
        shutil.copytree(str(doctrine_src), str(doctrine_dst), dirs_exist_ok=True)
        print(f"  created: doctrine/ ({_count_files(doctrine_dst)} files)")
    else:
        doctrine_dst.mkdir(exist_ok=True)
        (doctrine_dst / "README.md").write_text(
            "# doctrine/\n\nDoctor files will be placed here. "
            "Run `rv build-agents` to generate agent hats.\n",
            encoding="utf-8",
        )
        print(f"  created: doctrine/ (skeleton — doctrine source not found at {doctrine_src})")

    # ── Copy example loop manifests ──────────────────────────────────────────
    examples_src = _package_examples_dir()
    if examples_src.exists() and examples_src.is_dir():
        _copy_demo_project(
            examples_src / "demo-research",
            demo_research_dir,
            "demo-research",
        )
        _copy_demo_project(
            examples_src / "demo-litreview",
            demo_litreview_dir,
            "demo-litreview",
        )
    else:
        # Fallback: write placeholder manifests
        _write_placeholder_manifest(demo_research_dir, "research-loop-q1", "demo-research")
        _write_placeholder_manifest(demo_litreview_dir, "lit-review-loop-topic", "demo-litreview")
        print(f"  created: examples/ (placeholder manifests — source not found at {examples_src})")

    print()
    print("Research Vault instance initialised.")
    print()
    print("Next steps:")
    print("  1. rv check                     — verify prerequisites")
    print("  2. rv dag run examples/demo-research/research-loop.json  — start the research loop demo")
    print("  3. rv dag run examples/demo-litreview/lit-review-loop.json  — start the lit-review demo")
    print("  4. rv project add <slug> <path> — add a real project")
    print()
    print("See QUICKSTART.md for a full walkthrough.")
    return 0


def _copy_demo_project(src: Path, dst: Path, name: str) -> None:
    """Copy a demo project directory to the new instance."""
    if src.exists() and src.is_dir():
        shutil.copytree(str(src), str(dst), dirs_exist_ok=True)
        n = _count_files(dst)
        print(f"  created: examples/{name}/ ({n} files)")
    else:
        dst.mkdir(exist_ok=True)
        print(f"  created: examples/{name}/ (empty — source not found)")


def _write_placeholder_manifest(project_dir: Path, run_id: str, name: str) -> None:
    """Write a minimal placeholder manifest for a demo project."""
    manifest = {
        "run_id": run_id,
        "name": f"{name} (placeholder — re-init from a full install)",
        "global_cap": 2,
        "nodes": [
            {
                "id": "placeholder",
                "type": "agent",
                "label": "Placeholder node",
                "spec": f"task://{name}#placeholder",
                "needs": [],
            }
        ],
    }
    manifest_path = project_dir / f"{'research-loop' if 'research' in name else 'lit-review-loop'}.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")


def _count_files(path: Path) -> int:
    """Count files recursively in a directory."""
    return sum(1 for _ in path.rglob("*") if _.is_file())


# ---------------------------------------------------------------------------
# CLI verb
# ---------------------------------------------------------------------------

def build_parser(
    parent: "argparse._SubParsersAction | None" = None,
) -> argparse.ArgumentParser:
    """Build the argument parser for the ``init`` verb.

    When to use: ``rv init [<dir>]`` to scaffold a fresh Research Vault instance
    from templates. Creates the instance root with config, control files, task dirs,
    doctrine, notes root (OKF type dirs), and the two canned demo projects.
    """
    desc = (
        "Scaffold a fresh multi-project Research Vault instance. "
        "Creates research_vault.toml, control/, tasks/, doctrine/, notes/ (OKF type dirs), "
        "examples/demo-research/ + examples/demo-litreview/ demo projects, and QUICKSTART.md. "
        "A real project is a SEPARATE git repo registered via `rv project add`, not a subdir."
    )
    if parent is not None:
        p = parent.add_parser(
            "init",
            help="Scaffold a fresh Research Vault instance from templates.",
            description=desc,
        )
    else:
        p = argparse.ArgumentParser(prog="rv init", description=desc)

    p.add_argument(
        "dir",
        nargs="?",
        default=".",
        help="Directory to initialise (default: current directory).",
    )
    return p


def run(args: argparse.Namespace) -> int:
    """Dispatch: rv init [<dir>]."""
    return cmd_init_in_dir(args.dir)
