# SPDX-License-Identifier: AGPL-3.0-or-later
"""init.py — `rv init` — scaffold a fresh Research Vault instance.

When to use: ``rv init [<dir>]`` to scaffold a new multi-project Research Vault
instance in the given directory (or the current directory). Creates the instance
root with config, control files, task dirs, doctrine, and the notes root (OKF
type dirs).  Real projects are separate repos registered via ``rv project add``.

Claude Code (CC) binding additions:
  ``rv init`` also scaffolds the Claude Code binding so a bare
  ``rv init && claude`` boots Alfred + the full crew:
    1. Writes ``CLAUDE.md`` at the instance root (the hub-bootstrap: tells a
       fresh ``claude`` session that it IS Alfred, the hub).
    2. Creates an empty ``.claude/agents/`` dir (CC's session-start requirement:
       the watcher only registers dirs that exist before the session opens).
    3. Auto-runs ``build-agents --target claude-code`` to populate
       ``.claude/agents/<role>.md`` with CC-format subagent files for the
       DEFAULT_ROSTER (4 roles) + architect = 5 files (charter + role doctrine,
       vault-level — no per-project lens).

Multi-repo topology note:
  A REAL project is a separate git repo at an external source_dir, registered
  by ``rv project add``.
  ``rv init`` scaffolds the INSTANCE ROOT — it does NOT scaffold new projects as
  subdirs (that would re-introduce the monorepo pattern; use ``rv project add`` +
  the deferred ``rv project new`` capstone for real projects).

Framework materialization:
  Framework-managed files (CLAUDE.md, QUICKSTART.md, doctrine/**) are copied
  from package data via ``scaffold.py`` — the SAME helpers ``rv update`` uses,
  so a file added to one path can never be silently missing from the other.
  ``rv init`` also stamps ``[meta]`` in research_vault.toml + writes the
  ``.rv-manifest.json`` drift-detection sidecar, so ``rv update`` can later
  refresh the framework in place.

Package data layout:
  All files copied by ``rv init`` live under ``src/research_vault/data/`` inside
  the wheel.  They are loaded via ``importlib.resources`` + ``as_file()`` so the
  copy works from a regular wheel install AND from a zipped wheel (zipimport-safe).
  There are NO ``__file__``-based fallbacks — a missing data file is a HARD ERROR,
  not a silent skeleton (surface, never silently degrade).

Stdlib only. No external deps.
"""
from __future__ import annotations

import argparse
import contextlib
import io
import shutil
import subprocess
import sys
from pathlib import Path

from . import scaffold
from .note import scaffold_okf_dirs


# ---------------------------------------------------------------------------
# Config template
# ---------------------------------------------------------------------------

_CONFIG_TEMPLATE = """\
# research_vault.toml — Research Vault instance configuration
# Generated by `rv init`. Edit to add real projects and customise paths.
#
# Multi-repo topology: real projects are SEPARATE repos registered via `rv project add`.
#
# See QUICKSTART.md for the next steps.

instance_root = "{instance_root}"
notes_root = "{notes_root}"
state_dir = "{state_dir}"
agents_dir = "{agents_dir}"
tasks_dir = "{tasks_dir}"
control_dir = "{control_dir}"

[adapters]
notifier = "file"
backend = "local"
secrets = "env"

# ── To add a real project ────────────────────────────────────────────────────
# Convention: projects are SIBLINGS of the vault, each its own git repo.
# If this vault is at /home/user/myvault/, a new project lives at
# /home/user/my-project/ — NOT nested inside /home/user/myvault/.
#
# Stand up a brand-new project repo (git init + scaffold + crew) in one command:
#   rv project new my-project --code mp
#   → creates /home/user/my-project/ as a sibling (no --source needed)
#
# Register an existing repo:
#   rv project add my-project --code mp --source /path/to/my-project-repo
#
# Or add manually (source_dir MUST be outside the vault to avoid nested repos):
# [projects.my-project]
# source_dir = "/absolute/path/to/my-project-repo"  # sibling of this vault
"""

# ---------------------------------------------------------------------------
# Control file template
# ---------------------------------------------------------------------------

_CONTROL_TEMPLATE = """\
# CONTROL — {project}

The hub↔crew bus for this project: an async, durable handshake file.
READ via `rv status {project}` or `rv control {project} check`.
WRITE via `rv control {project} post <text>` — never by hand.

> *Created by `rv init`.*

## Inbox  (hub/owner → crew)
  _(none)_

## Handshakes  (in-flight, needs the other side)
  _(none)_

## Outbox  (crew → hub/owner)
  _(none)_

## Open / blockers
  _(none)_
"""

# ---------------------------------------------------------------------------
# DEVLOG template
# ---------------------------------------------------------------------------

_DEVLOG_TEMPLATE = """\
# DEVLOG

Newest entry on top. One entry per working day.
Sections: ### Done · ### Decisions · ### Open / next

---

## {today} — Instance initialised

### Done
- `rv init` scaffolded this Research Vault instance.

### Decisions
- Instance root: `{instance_root}`

### Open / next
- Run `rv check` to verify prerequisites.
- Add a real project: `rv project add <slug> <path>`
"""

# ---------------------------------------------------------------------------
# architecture.md template
# ---------------------------------------------------------------------------

_ARCHITECTURE_TEMPLATE = """\
# Architecture

This file documents the structure and design decisions for this Research Vault instance.

> *This file is USER-OWNED — the architect's living map. `rv update` never
> regenerates it.*

## Instance layout

```
{instance_root}/
  research_vault.toml   # config SSOT — all paths resolved here
  QUICKSTART.md         # getting-started guide
  DEVLOG.md             # decision log (newest first)
  architecture.md       # this file
  notes/                # central OKF knowledge base
    experiments/        # pre-registration notes (filed before runs)
    findings/           # research findings
    methods/            # method and protocol notes
    literature/         # distilled literature notes
    concepts/           # distilled conceptual claims
    mocs/               # maps of content (link graphs)
  control/              # coordination bus (one file per project)
  tasks/                # task cards (one subdir per project)
  doctrine/             # portable research-assistant doctrine
  .agents/              # agent hat files (generated by rv build-agents)
```

## Multi-project registry

Projects are registered in `research_vault.toml` under `[projects.<slug>]`.
Each project has a `source_dir` pointing to its repository root.

Register a real project (a separate repo): `rv project add <slug> <path>`

## The three canonical loops

### Experiment loop

```
plan → plan-critic → [human-go-plan] → harness (×N mains) → harness-review
    → [human-go-harness] → run → score → analyze → [human-go-findings]
```

Pre-registration is **structural**: each main's `run` node has an `afterok`
watch on the pre-registration note (and its own harness is reviewed
independently before its own human-go gate). The experiment cannot run until
the note exists.

### Lit-review loop (pre-registered, citation-neighbor relevance walk)

Phase-1 (discovery):
```
review-scope → [approve-protocol] → review-search → review-screen
    → review-snowball → review-curate → [coverage-gate]
```

Phase-2 (per-paper distillation + synthesis, fanned out after coverage-gate approval):
```
relate-<key> (×N papers) → review-synthesize → review-coverage-critic → [approve-review]
```

The protocol must be approved (Gate 1) before search fires — the L-2
anti-fishing gate. `review-search`/`review-snowball` are deterministic TOOL
nodes (width-sweep, both-direction snowball); `review-screen`/`review-curate`
are thin agent judgment layers. `coverage-gate` (Gate 2) is the phase
boundary: it authorizes the Phase-2 relate fan-out, and every relate-<key>
node cannot succeed without its `literature/<key>.md` note (enforced by
`rv dag complete`'s produces check).

### Manuscript loop

```
[approve-framework] (type-specific Phase-1, e.g. lit-review's framework
    selection) → draft sections → structural/fidelity gates + review-revise
    board → [approve-manuscript]
```

Transforms the OKF pillar (`notes/`) into a submittable document. Every
registered manuscript type shares the terminal `approve-manuscript` gate.
"""

# ---------------------------------------------------------------------------
# .gitignore template — SSOT is scaffold.FRAMEWORK_GITIGNORE (shared with update)
# ---------------------------------------------------------------------------

_GITIGNORE_CONTENT = scaffold.FRAMEWORK_GITIGNORE

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _git_init_vault(target: Path, *, verbose: bool = False) -> None:
    """git-init the vault root, write .gitignore, and make an initial commit.

    Runs entirely under subprocess so the package stays stdlib-only.
    Failures are surfaced as loud warnings (never crash the scaffold —
    the vault is useful even without git, just not bootable by Claude Code).

    Uses ``--initial-branch=main`` to satisfy the lint rule (branch is
    deterministic regardless of the runner's git.defaultBranch setting).

    A local identity (``-c user.name`` / ``-c user.email``) and
    ``commit.gpgsign=false`` are injected via ``-c`` flags so the commit
    works in bare CI/CD or fresh-laptop environments that have no global
    git config.  These flags affect only this one subprocess call.

    ``verbose`` — when False (the default), suppresses the success line.
    """
    if shutil.which("git") is None:
        print(
            "rv init: WARNING — git not found on PATH.\n"
            "  The vault is not a git repository. Claude Code (Bun) needs one to boot.\n"
            "  Install git, then run: git init && git add -A && git commit -m 'initial vault scaffold'\n"
            "  in the vault directory.",
            file=sys.stderr,
        )
        return

    # ── git init ──────────────────────────────────────────────────────────
    r = subprocess.run(
        ["git", "init", "--initial-branch=main", str(target)],
        capture_output=True, text=True,
    )
    if r.returncode != 0:
        print(
            f"rv init: WARNING — git init failed ({r.stderr.strip()}).\n"
            "  The vault is not a git repository. Run `git init` manually.",
            file=sys.stderr,
        )
        return

    # ── Write .gitignore ──────────────────────────────────────────────────
    (target / ".gitignore").write_text(_GITIGNORE_CONTENT, encoding="utf-8")

    # ── Stage all scaffold files ──────────────────────────────────────────
    r = subprocess.run(
        ["git", "-C", str(target), "add", "-A"],
        capture_output=True, text=True,
    )
    if r.returncode != 0:
        print(
            f"rv init: WARNING — git add failed ({r.stderr.strip()}).\n"
            "  The vault is initialised as a git repo but has no initial commit.\n"
            "  Run `git add -A && git commit -m 'initial vault scaffold'` manually.",
            file=sys.stderr,
        )
        return

    # ── Make initial commit (local identity + no GPG signing) ────────────
    r = subprocess.run(
        [
            "git",
            "-C", str(target),
            "-c", "user.name=rv init",
            "-c", "user.email=rv-init@example.invalid",
            "-c", "commit.gpgsign=false",
            "commit",
            "-m", "initial vault scaffold",
        ],
        capture_output=True, text=True,
    )
    if r.returncode != 0:
        print(
            f"rv init: WARNING — initial git commit failed ({r.stderr.strip()}).\n"
            "  The vault is a git repo but has no initial commit.\n"
            "  Run `git commit -m 'initial vault scaffold'` manually.",
            file=sys.stderr,
        )
        return

    if verbose:
        print("  git: initialised repo + initial commit (branch: main)")


# ---------------------------------------------------------------------------
# Core init logic
# ---------------------------------------------------------------------------

def cmd_init_in_dir(target_dir: str, *, verbose: bool = False) -> int:
    """Scaffold a fresh Research Vault instance in target_dir.

    Returns 0 on success, 1 on error.
    This is the programmatic entrypoint (also used by tests).

    ``verbose`` — when True, print every created/written/build-agents/git line
    (the old default behaviour, now opt-in via ``--verbose``).  When False
    (the default), only the terse success block is printed.
    """
    import datetime

    target = Path(target_dir).expanduser().resolve()

    # Guard: refuse to overwrite an existing instance
    config_path = target / "research_vault.toml"
    if config_path.exists():
        print(
            f"rv init: {config_path} already exists. "
            "Research Vault is already initialised here. "
            "Remove research_vault.toml to re-initialise.",
            file=sys.stderr,
        )
        return 1

    if not target.exists():
        target.mkdir(parents=True)

    print(f"Initialising Research Vault instance in: {target}")

    # Verbose-gated print helper — all file inventory lines go through this.
    def vprint(msg: str) -> None:
        if verbose:
            print(msg)

    # ── Resolve all paths ────────────────────────────────────────────────────
    notes_root = target / "notes"
    state_dir = target / "state"
    agents_dir = target / ".agents"
    tasks_dir = target / "tasks"
    control_dir = target / "control"

    # ── Create directory structure ───────────────────────────────────────────
    for d in (
        notes_root,
        state_dir,
        agents_dir,
        tasks_dir,
        control_dir,
    ):
        d.mkdir(parents=True, exist_ok=True)
        vprint(f"  created: {d.relative_to(target)}/")

    # ── Create OKF note type dirs ────────────────────────────────────────────
    scaffold_okf_dirs(notes_root)
    for note_type in sorted({"experiments", "findings", "methods", "literature", "concepts", "mocs"}):
        vprint(f"  created: notes/{note_type}/")

    # ── Write research_vault.toml ────────────────────────────────────────────
    today_str = datetime.date.today().isoformat()
    config_text = _CONFIG_TEMPLATE.format(
        instance_root=str(target),
        notes_root=str(notes_root),
        state_dir=str(state_dir),
        agents_dir=str(agents_dir),
        tasks_dir=str(tasks_dir),
        control_dir=str(control_dir),
    )
    config_path.write_text(config_text, encoding="utf-8")
    vprint(f"  created: research_vault.toml")

    # ── Write DEVLOG.md ──────────────────────────────────────────────────────
    devlog_text = _DEVLOG_TEMPLATE.format(
        today=today_str,
        instance_root=str(target),
    )
    (target / "DEVLOG.md").write_text(devlog_text, encoding="utf-8")
    vprint(f"  created: DEVLOG.md")

    # ── Write architecture.md (USER-OWNED — never regenerated by rv update) ──
    arch_text = _ARCHITECTURE_TEMPLATE.format(instance_root=str(target))
    (target / "architecture.md").write_text(arch_text, encoding="utf-8")
    vprint(f"  created: architecture.md")

    # ── Write the default control file (vault-level bus) ─────────────────────
    ctrl_text = _CONTROL_TEMPLATE.format(project="vault")
    (control_dir / "vault.md").write_text(ctrl_text, encoding="utf-8")
    vprint(f"  created: control/vault.md")

    # ── Copy framework-managed statics via the SHARED scaffold helpers ───────
    # CLAUDE.md, QUICKSTART.md, doctrine/** — the SAME enumeration `rv update`
    # consumes, so a managed file can never be init-only (invisible-on-upgrade).
    managed_hashes = scaffold.write_managed_statics(target)
    doctrine_files = sum(1 for k in managed_hashes if k.startswith("doctrine/"))
    vprint(f"  created: CLAUDE.md")
    vprint(f"  created: QUICKSTART.md")
    vprint(f"  created: doctrine/ ({doctrine_files} files)")

    # ── Create .claude/agents/ dir (CC session-start requirement) ────
    # CC's file watcher registers .claude/agents/ only if it exists when the
    # session opens.  Create it now (even before populating) so a bare
    # `rv init && claude` works without a manual restart.
    dot_claude_agents = target / ".claude" / "agents"
    dot_claude_agents.mkdir(parents=True, exist_ok=True)
    vprint(f"  created: .claude/agents/")

    # ── Auto-run build-agents --target claude-code ───────────────────
    # Populate .claude/agents/<role>.md with CC-format subagent files so the
    # crew is discoverable immediately (zero extra commands for the adopter).
    #
    # IMPORTANT — why we do NOT use load_config() here:
    #   The rv CLI calls load_config() at dispatch time (cli.py: cfg = load_config())
    #   to resolve instance-level plugin verbs.  That call populates the module-level
    #   _CACHE with a stale config — typically the default (no projects, CWD as
    #   instance_root) because `rv init myvault` is run from the PARENT directory
    #   before the new research_vault.toml even exists.  A subsequent load_config()
    #   call here would hit that stale cache regardless of any env-var override, and
    #   the auto-build would write files to the WRONG instance_root.
    #
    #   Fix: construct Config directly from the TOML we just wrote, bypassing the
    #   module-level cache entirely.  This is immune to cache state and always reads
    #   exactly what we persisted above.
    from .config import (
        Config, _load_toml, _expand_paths, _default_config, _merge, reset_config_cache,
    )
    from .build_agents import cmd_build as _cmd_build_agents
    from .project import DEFAULT_ROSTER as _DEFAULT_ROSTER
    try:
        _defaults = _default_config()
        _raw = _load_toml(config_path)
        _merged = _merge(_defaults, _raw)
        # instance_root is written as an absolute path in the TOML by _CONFIG_TEMPLATE;
        # fall back to `target` if somehow absent.
        _instance_root = Path(_merged.get("instance_root", str(target)))
        _merged = _expand_paths(_merged, _instance_root)
        _cfg = Config(_merged, config_file=config_path)
        # Reset the module-level cache so subsequent rv commands in the same process
        # reload from the new instance's config rather than any stale pre-init cache.
        reset_config_cache()

        # Suppress build-agents stdout when not verbose; stderr (warnings) always visible.
        _sink: io.StringIO | None = None if verbose else io.StringIO()
        with contextlib.redirect_stdout(sys.stdout if verbose else _sink):  # type: ignore[arg-type]
            _rc = _cmd_build_agents(cfg=_cfg, target="claude-code")
        if _rc != 0:
            print(
                "rv init: WARNING — build-agents --target claude-code returned non-zero. "
                "Run `rv build-agents --target claude-code` manually to populate .claude/agents/.",
                file=sys.stderr,
            )
        # Post-build assertion (reviewer hardening): verify the expected agent files actually
        # exist.  A silent zero-exit with 0 files is more dangerous than a loud failure.
        _agents_dir = _instance_root / ".claude" / "agents"
        _present = list(_agents_dir.glob("*.md")) if _agents_dir.is_dir() else []
        _expected_count = len(_DEFAULT_ROSTER) + 1  # DEFAULT_ROSTER roles + architect
        if len(_present) < _expected_count:
            _missing = _expected_count - len(_present)
            print(
                f"rv init: ERROR — build-agents wrote {len(_present)} agent file(s) but "
                f"{_expected_count} were expected ({_missing} missing). "
                "The crew is incomplete. "
                "Run `rv build-agents --target claude-code` manually to investigate.",
                file=sys.stderr,
            )
            return 1
    except Exception as exc:
        print(
            f"rv init: WARNING — could not auto-run build-agents (claude-code): {exc}. "
            "Run `rv build-agents --target claude-code` manually to populate .claude/agents/.",
            file=sys.stderr,
        )

    # ── Version stamp — [meta] block + .rv-manifest.json ────────
    # Written at init AND update so `rv update` can compare the vault's shipped
    # version against the installed package and refresh in place.
    now_iso = datetime.datetime.now(datetime.timezone.utc).replace(microsecond=0).isoformat()
    fw_version = scaffold.package_version()
    try:
        _toml_text = config_path.read_text(encoding="utf-8")
        _toml_text = scaffold.upsert_meta_block(
            _toml_text,
            framework_version=fw_version,
            scaffolded_at=now_iso,
            updated_at=now_iso,
        )
        config_path.write_text(_toml_text, encoding="utf-8")
        # Manifest records BOTH the statics AND the freshly-composed hats.
        _managed = dict(managed_hashes)
        _managed.update(scaffold.hash_hats(target))
        scaffold.write_manifest(target, framework_version=fw_version, managed=_managed)
        vprint(f"  created: {scaffold.MANIFEST_NAME} (framework v{fw_version})")
    except Exception as exc:
        print(
            f"rv init: WARNING — could not write version stamp / manifest: {exc}. "
            "`rv update` staleness detection may not work until you re-run `rv init` "
            "or `rv update`.",
            file=sys.stderr,
        )

    # ── git init + .gitignore + initial commit ───────────────────────────────
    # Runs AFTER the full scaffold (including build-agents) so the initial
    # commit captures all generated files.  Graceful on failure — warn, never
    # crash a successful scaffold.
    _git_init_vault(target, verbose=verbose)

    # ── Closing block — rich at a TTY, plain otherwise ────────────────────────
    from .richui import render_init as _render_init
    _render_init({"target": str(target), "target_name": target.name})

    return 0


def _count_files(path: Path) -> int:
    """Count files recursively in a directory."""
    return scaffold.count_files(path)


# ---------------------------------------------------------------------------
# CLI verb
# ---------------------------------------------------------------------------

def build_parser(
    parent: "argparse._SubParsersAction | None" = None,
) -> argparse.ArgumentParser:
    """Build the argument parser for the ``init`` verb.

    When to use: ``rv init [<dir>]`` to scaffold a fresh Research Vault instance
    from templates. Creates the instance root with config, control files, task dirs,
    doctrine, and the notes root (OKF type dirs). Real projects are separate repos
    registered via ``rv project add``.
    """
    desc = (
        "Scaffold a fresh multi-project Research Vault instance. "
        "Creates research_vault.toml, control/, tasks/, doctrine/, notes/ (OKF type dirs), "
        "CLAUDE.md, and QUICKSTART.md. "
        "A real project is a SEPARATE git repo registered via `rv project add`, not a subdir."
    )
    if parent is not None:
        p = parent.add_parser(
            "init",
            help="Scaffold a fresh Research Vault instance from templates.",
            description=desc,
        )
    else:
        p = argparse.ArgumentParser(prog="rv init", description=desc)

    p.add_argument(
        "dir",
        nargs="?",
        default=".",
        help="Directory to initialise (default: current directory).",
    )
    p.add_argument(
        "--verbose",
        action="store_true",
        default=False,
        help=(
            "Print the full file inventory (created:, Written:, build-agents, git lines). "
            "Default is terse: only the summary + next-steps block."
        ),
    )
    return p


def run(args: argparse.Namespace) -> int:
    """Dispatch: rv init [<dir>]."""
    return cmd_init_in_dir(args.dir, verbose=getattr(args, "verbose", False))
